### ISSUE TITLE
Maybe have the OLM-logo on the first page instead of a smiley

### ISSUE THREAD

**Issue by FredMark** [OpenLitterMap/react-native#10]
see screenprint.

This is what you see if you are new and not yet logged in.

It could be me, but the smiley seems to downgrade the app.
Almost as if it is just an app that you download, use 2 times and then remove again.
I think this first screen could do with a little redesign, make it more 'mature' (maybe with the OLM-logo on it,
and some call-to-action like 'make a change' or 'be the change you want to see', 
![IMG_5242](https://user-images.githubusercontent.com/2518047/101998988-911afe80-3cd8-11eb-9714-6700d1156878.PNG)
'create some impact' or something like that.

**Comment by xlcrr** [comment]
Design should be moved to discussion, issues for app bugs
