### ISSUE TITLE
Image of litter not shown on map

### ISSUE THREAD

**Issue by martinstingl** [OpenLitterMap/react-native#105]
Hi,
I tried to upload my first litter image but it is not shown on the map after several days.
What am I doing wrong or is this a bug?

![20210905_153403-little](https://user-images.githubusercontent.com/1312947/133820158-25e3683e-0b00-4586-9e86-e8860dd09f7c.jpg)

**Comment by sudoDeznit** [comment]
@martinstingl there is a verification process. Admin needs to approve the image before its shown on the map as cluster.
but if you zoom enough to your location you will be able to see a Green dot at that location

**Comment by martinstingl** [comment]
Thank you, I was not expecting the verification process takes so long.

**Comment by xlcrr** [comment]
Hi, if you zoom in, the dot will show right away. For new users, its grey until verified. For trusted users, they skip verification. This will be automated by the AI later. Clusters update irregularly. There is a command to update them. This is currently being refactored by a developer and the new command will happen more regularly
