### ISSUE TITLE
Not clear how you should take some photos with the app itself

### ISSUE THREAD

**Issue by FredMark** [OpenLitterMap/react-native#11]
see screenprint.

When you use the app for the first time and just logged in, you get to see the camera and you can start to make some pictures.
However, if you are using it for a while (for instance you took a picture and managed to delete the picture), you get this green screen with a message 'take or select some photos to get started'.
The button top-left is settings,
The button bottom is the place where you can select some photos,
But it is not clear how/where you were able to take new pictures.
The text in the middle of the screen is not 'clickable', 
It takes some time to realize that you can actually swipe this screen.

Maybe some redesign to make this more obvious.
![IMG_5243](https://user-images.githubusercontent.com/2518047/101999070-86149e00-3cd9-11eb-8e56-fdebd3d5e49e.PNG)

**Comment by sudoDeznit** [comment]
added camera icon in bottom tabbar to go back to camera page. d22232f2174ad726acc588caa770366acfc6a76b
