### ISSUE TITLE
Consistent crashes on iPhone 12 mini (OLM Version 2.0.9, iOS 14.2.1)

### ISSUE THREAD

**Issue by habi** [OpenLitterMap/react-native#17]
I start OLM (Version 2.0.9) on my iPhone 12 mini (iOS 14.2.1), take a photo, tap to upload and the app consistently crashes.
Photos taken like this are not saved to the Photos library, so they can also not be uploaded later on.

Attached is a short screencast from the phone which I resized from 886x1920 to 480x1040 to fit into the 10 MB upload limit of GitHub.

https://user-images.githubusercontent.com/1651235/102771781-c681b500-4386-11eb-9c7c-2a558819cb24.mp4

**Comment by xlcrr** [comment]
Thanks for the report and video.

Are you able to select, tag and upload photos taken from your normal camera app?

Not sure why this is crashing and I don't have an actual iPhone 12 device to replicate... I will try the simulator but if you / anyone can download the code and test on a device that would be appreciated 

I will get back to working and debugging the mobile app very soon!

Thanks

**Comment by habi** [comment]
> Are you able to select, tag and upload photos taken from your normal camera app?

Select yes, tag and upload no.

**Comment by xlcrr** [comment]
Good to know thanks.

What happens when you try to tag or upload? It just crashes?

If you can try to log out and back in it might help

**Comment by habi** [comment]
> What happens when you try to tag or upload? It just crashes?

I can select the photo form the Photos library and It shows up. Selecting it afterwards crashes the app.

> If you can try to log out and back in it might help

This did not help.￼

**Comment by xlcrr** [comment]
Bug on simulator confirmed

Our code was written before iPhone 12 was released, and when we check for `DeviceInfo.getModel()` which should return "iPhone 12" it only returns iPhone 

[https://github.com/OpenLitterMap/react-native/blob/master/screens/pages/components/LeftPageImages.js#L243](https://github.com/OpenLitterMap/react-native/blob/master/screens/pages/components/LeftPageImages.js#L243
)

I will be upgrading react-native and all packages today, this fix will be included in the next release

**Comment by xlcrr** [comment]
First bug fixed locally....

```
[Sat Dec 26 2020 13:31:00.761]  LOG      device iPhone 12
[Sat Dec 26 2020 13:31:00.763]  LOG      {"x": "12"}
```

**Comment by xlcrr** [comment]
Hi @habi 

This should be fixed in the latest update.

Can you confirm? 

Thanks!

**Comment by habi** [comment]
> This should be fixed in the latest update.

Under the app does not crash anymore.
Upload does not work though, the app never goes past the modal uploading screen, see attachment.

![image](https://user-images.githubusercontent.com/1651235/103455966-f8cdd380-4cf1-11eb-9f0a-88df1fcb6dd8.png)

**Comment by xlcrr** [comment]
Thanks

It seems like this photo is not geotagged

Did you select it with the OLM camera or from your photo gallery? (It should not appear in your gallery if it is not geotagged).

If you select a geotagged photo, it should work

**Comment by habi** [comment]
> On 2 Jan 2021, at 14:09, xlcrr <notifications@github.com> wrote:
> 
> Did you select it with the OLM camera or from your photo gallery?

Directly from the OLM camera that shows up on the first screen.

**Comment by xlcrr** [comment]
I will debug this today, thanks for pointing this out

If you use the default camera on your device to take geotagged photos, you should be able to upload them

**Comment by habi** [comment]
'External' photos can be uploaded.
So I'm closing this issue.

**Comment by xlcrr** [comment]
Good to know, thanks!

Another bug with camera will be fixed by https://github.com/OpenLitterMap/react-native/pull/33 in the next update
