### ISSUE TITLE
possible to choose a tag twice

### ISSUE THREAD

**Issue by FredMark** [OpenLitterMap/react-native#2]
Open the OLM-app,
choose a picture from your gallary to upload, for instance a facemask
go to the tagging screen,
use the textfield and type 'face',
'sanitary - facemask' appears as a possible tag
select this tag.
Tap on the picture so the input-field disappears,
At this moment you see the picture, with 1 tag: 'Facemask (1)'. This is okay.

Now, tap on '+ add tag'.

The result:
The picture with 2 tags:
'Facemask (1)' and another one: 'Facemask (1).

Normally when you tap 'Add tag', the number increases (and indeed, after tapping 'Add tag' once more, the tag on the right changes to 'Facemask (2)'. This should have happened in the first case.
![IMG_5235](https://user-images.githubusercontent.com/2518047/101995419-f9aeaf00-3cc9-11eb-816a-65c41968c049.PNG)

**Comment by xlcrr** [comment]
Fixed locally
