### ISSUE TITLE
change the order of the buttons

### ISSUE THREAD

**Issue by FredMark** [OpenLitterMap/react-native#20]
if you are tagging an item, (and you have already given 1 tag),
you have to be careful to use 'add tag' and not 'confirm', because in the last case, the picture will disappear without the change to give the tag that you wanted to add.
However, the 'confirm' is on the left and the 'add tag' is on the right.
It would make sense to switch those.
(you read/flow from top to bottom and from left to right.
So first all the 'confirm tags' on the left, and if you are done, you move to the right and select 'confirm'.
(maybe it would even be wise to move the confirm to a totally other location, so you don't press it unintentionally.

I think that this should be changed as soon as possible, before too many new users are used to this 'wrong' order.
![IMG_4320](https://user-images.githubusercontent.com/2518047/103310273-77d3bb00-4a17-11eb-9b9d-597f69ac826b.png)

**Comment by xlcrr** [comment]
The idea behind this order is that more right are right-handed, and "Add-tag" will be pressed more frequently than confirm

**Comment by FredMark** [comment]
Ah, i see.
Sounds good.
Leave it this way.
I'll close it.
