### ISSUE TITLE
Android App doesn't appear to be able to display photos

### ISSUE THREAD

**Issue by mustyoshi** [OpenLitterMap/react-native#205]
With the latest version it doesn't seem to load my photos, even after turning location services on.
Scrolling makes it seem like it sees the photos but just can't display them, because further down it denotes different time scales consistent with if it was actually tiling my photos.

![image](https://user-images.githubusercontent.com/1816047/198291554-2f6f1838-a67d-48a9-a6b9-d0674f0d0d5d.png)

I'll try messing around with the app locally at some point.

**Comment by xlcrr** [comment]
Hi Bradley,

Good to know thanks.

Haven't seen this issue before... can you confirm what kind of a device you are using?

**Comment by mustyoshi** [comment]
Moto G Power
Android 10

**Comment by mustyoshi** [comment]
I see the target sdk version is 30, which may be my problem, android 10 only has api level 29?

**Comment by mustyoshi** [comment]
😅 I'm having trouble running it locally
```
PS C:\Users\Bradley\Github\olm-react-native> npx react-native run-android --deviceId [My-Physical-device]
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 1256 file(s) to forward-jetify. Using 12 workers...
info JS server already running.
info Building the app...

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
A problem occurred evaluating project ':app'.
> A problem occurred starting process 'command 'security''

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':app'.
> com.android.builder.errors.EvalIssueException: compileSdkVersion is not specified. Please add it to build.gradle

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
error Failed to build the app. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat build -x lint
    at makeError (C:\Users\Bradley\Github\olm-react-native\node_modules\execa\index.js:174:9)
```

**Comment by mustyoshi** [comment]
I upgraded my phone to Android 11, and the image display is working now.

**Comment by xlcrr** [comment]
Great to know!! Thanks for the update. We should detect this in the app and tell users to upgrade if its a problem. Closing this for now, but I will add a card to Trello with this task. Thanks for helping to improve openlittermap! This would be a great task to get started with
