### ISSUE TITLE
v2.0.11, wrong category shown if you 're-choose' the same tag

### ISSUE THREAD

**Issue by FredMark** [OpenLitterMap/react-native#21]
This bug will probably not exist if https://github.com/OpenLitterMap/react-native/issues/2 is solved.

I have uploaded a picture and i searched for 'bottle' in the searchfield.
I found the right one: 'SoftDrinks - Juice Bottles' and i select that one.
Because it still feels like you have to add the tag, i also press 'Add tag' which results in (see issue 2) adding another same tag, also Juice Bottles.
However, in this case you also see that the category is said to be 'Smoking' (probably because that is the 'active' category in the top of the screen.
Not sure what will happen if i continue, so i will just delete the 2nd tag, but maybe it would result in adding 2 tags.

![IMG_6005](https://user-images.githubusercontent.com/2518047/103368192-41ee0f80-4ac7-11eb-8a15-02f8f88a0e17.PNG)

**Comment by xlcrr** [comment]
Fixed locally. Will be included in the next release.
