### ISSUE TITLE
Wish: give a message when starting the app and if a newer version is available in the app-store

### ISSUE THREAD

**Issue by FredMark** [OpenLitterMap/react-native#22]
When a new version is available in the app-story, we hear about it via Slack etc.
However, if you open the app on your iphone, you just open the old version without knowing that a newer version is available.

I also use other apps and if a new version is available, i get a message after opening that app that says something like 
"new version available" with 2 options:
[update[ / [later]

I think this would be a nice way to let users know that there is a newer version.
(The update via the button is nice as well of course, but a user can also visit the app store and update it there)

**Comment by xlcrr** [comment]
https://github.com/redbooth/react-native-auto-updater

**Comment by sudoDeznit** [comment]
@FredMark closing this issue because this feature is now added.
