### ISSUE TITLE
Possible Littercoin-problem when multiple items in 1 picture

### ISSUE THREAD

**Issue by FredMark** [OpenLitterMap/react-native#24]
Yesterday i found and photographed 2 cans in 1 picture.

This got me thinking:
i can tag 2 cans in one picture, i would earn 4xp, i think.
i can take 2 pictures, each with one can and tag both of them, that would also give me 4xp, i think.

However, (at this moment you don't see anything about littercoins, so i can not check it),
As far as i know you get 1 littercoin for every 100 pictures that are approved.

So, if you take 2 separate pictures and do that 50 times, you will earn 1 littercoin.
However, if you take 1 picture with 2 items, you will have to do that 100 times, to earn 1 littercoin?

The solution: don't calculate the number of pictures that are approved in a row,
But the number of items on it.

**Comment by xlcrr** [comment]
Closing this for now until we start on Littercoin again, too much going on. Littercoin will be discussed seperately later
