### ISSUE TITLE
Possible tag missing when using the text-search field

### ISSUE THREAD

**Issue by FredMark** [OpenLitterMap/react-native#3]
I have uploaded some pictures and i want to tag them.
The first one is plastic so i use the textfield (really nice feature!), and type 'plastic'. 6 results are given, but none of them applies to the item that i am looking at. However, it really is plastic so i have to choose 1 of them...
However, i am 100% sure that there is also a tag with the name 'unidentified plastic' that is not in this list of 6.

Bug: if I remove the text that I entered, and start with 'unidenti', I get the missing option: 'unidentified plastic'. There seems to be a limit in the tags that are shown. There shouldn't be a limit.
If people don't know what tags are really available and search on 'plastic', they should get all tags containing 'plastic'.

**Comment by xlcrr** [comment]
Currently 6 items are given when you type something.... a number that was chosen at random. Easy to increase this number, but maybe we should do more?

**Comment by FredMark** [comment]
I think there should not be a limit.
Hopefully what the user is looking for is within the first (let's say) 3 items, but if not, he should be able to scroll through the tags that are presented to get the one that he needs.
(of course, if it is possible to type more letters as a user to narrow down the results, that would be the good way to work,
but it would not have to be the only way to get to the result, just typing a few letters and then start scrolling through all possible results should also be possible, (i think).

**Comment by xlcrr** [comment]
Easy PR fix here for someone who wants to make a contribution!

**Comment by FredMark** [comment]
This one is already solved, i think?

**Comment by FredMark** [comment]
Confirmed just now, this one is solved already.
