### ISSUE TITLE
Upload via app gives less xp's than same upload via web

### ISSUE THREAD

**Issue by FredMark** [OpenLitterMap/react-native#37]
Upload 1 redbull-photo.
On web you get 1 xp for the photo and 2 xp for the 2 tags (energy-can & redbull)

Upload a similar photo via the app.
In total you only get 2 xp. (not sure if the upload of the photo is not awarded, or that it is, but 1 tag is not awarded).

**Comment by sudoDeznit** [comment]
@GeniJaho is this fixed or still an issue?

**Comment by GeniJaho** [comment]
@sudoDeznit This has been fixed apparently. Here's the Trello card for this issue https://trello.com/c/nCFjS3xr. We can close it.
