### ISSUE TITLE
iOS app continuously accesses camera

### ISSUE THREAD

**Issue by zorae** [OpenLitterMap/react-native#49]
On iOS, even while tagging or uploading photos, the app continuously accesses the camera. This can be observed by the green dot in the status bar. This is scary. Instead, camera access should only occur while the in-app camera is active.

**Comment by xlcrr** [comment]
So that's what the green dot means! This should be fixed as its also probably a drain on the battery

**Comment by xlcrr** [comment]
Investigating this, but I can't find any API to disconnect after swipe. Any suggestions?
