### ISSUE TITLE
Not possible to swipe to next picture on app, when pictures are uploaded via web

### ISSUE THREAD

**Issue by FredMark** [OpenLitterMap/react-native#50]
I upload the pictures on web. The are shown there and it is possible to tag them and jump to any picture that you want or to go to previouw/next picture (without tagging the current one).

It used to be possible to do the same on mobile-app,
so upload the pictures via web, but then open the app to tag the pictures.
However, it is not possible anymore to swipe to the next picture (without tagging the current one).
If you swipe, the screen goes to the next picture, a 'wheel' is shown that keeps spinning like it is loading the next picture, but it stays like that, the next picture does not appear.
If you swipe back to the 1st picture, then that one loads correctly.

**Comment by xlcrr** [comment]
Fixed
