### ISSUE TITLE
not clear what the switch is meant for

### ISSUE THREAD

**Issue by FredMark** [OpenLitterMap/react-native#8]
If you are tagging a picture on the phone, in the right bottom, there is a switch. It is 'on', but it is not clear what it is meant for (no text, just a switch).
If you turn it off, it says 'the litter is still there' so i guess that if you leave it set to 'on' you indicate that the litter has been picked? Maybe think about some design that makes it more clear what it is/does.
![IMG_5241](https://user-images.githubusercontent.com/2518047/101998745-3b455700-3cd6-11eb-9a6e-05a526f3d40f.PNG)

**Comment by xlcrr** [comment]
Switch removed
