### ISSUE TITLE
Not obvious that the 'log in' is actually a link to the login page

### ISSUE THREAD

**Issue by FredMark** [OpenLitterMap/react-native#9]
See print screen.

If you are not logged in, you get this screen,
Although it mentions you to log in, it is not clear how/where.

It turns out that the text itself is a link to the login page.
It would be better for visibility if that text was underlined or something like that.
![IMG_5242_login](https://user-images.githubusercontent.com/2518047/101998935-0df9a880-3cd8-11eb-998c-ad0671dd062c.png)

**Comment by sudoDeznit** [comment]
@FredMark closing this because this screen was restyled
